### ISSUE TITLE
1.0 doesn’t compile with enchant 1.5.0 on CentOS 6.5 (rpmbuild)

### ISSUE THREAD

**Issue by lwandrebeck** [weechat/weechat#192]
```
Scanning dependencies of target aspell
make[2]: Leaving directory `/home/low/build/BUILD/weechat-1.0/build'
make -f src/plugins/aspell/CMakeFiles/aspell.dir/build.make src/plugins/aspell/CMakeFiles/aspell.dir/build
make[2]: Entering directory `/home/low/build/BUILD/weechat-1.0/build'
/usr/bin/cmake -E cmake_progress_report /home/low/build/BUILD/weechat-1.0/build/CMakeFiles 2
[ 25%] Building C object src/plugins/aspell/CMakeFiles/aspell.dir/weechat-aspell.o
cd /home/low/build/BUILD/weechat-1.0/build/src/plugins/aspell && /usr/bin/gcc  -Daspell_EXPORTS -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -DENABLE_NLS -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ZLIB -DHAVE_ICONV -DWEECHAT_VERSION=\"1.0\" -DWEECHAT_LICENSE=\"GPL3\" -DUSE_ENCHANT -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -Wall -Wextra -Werror-implicit-function-declaration -fPIC -I/home/low/build/BUILD/weechat-1.0/build -I/usr/include/enchant    -fPIC -o CMakeFiles/aspell.dir/weechat-aspell.o   -c /home/low/build/BUILD/weechat-1.0/src/plugins/aspell/weechat-aspell.c
/home/low/build/BUILD/weechat-1.0/src/plugins/aspell/weechat-aspell.c: In function 'weechat_aspell_debug_libs_cb':
/home/low/build/BUILD/weechat-1.0/src/plugins/aspell/weechat-aspell.c:1005: error: implicit declaration of function 'enchant_get_version'
make[2]: *** [src/plugins/aspell/CMakeFiles/aspell.dir/weechat-aspell.o] Error 1
make[2]: Leaving directory `/home/low/build/BUILD/weechat-1.0/build'
make[1]: *** [src/plugins/aspell/CMakeFiles/aspell.dir/all] Error 2
make[1]: Leaving directory `/home/low/build/BUILD/weechat-1.0/build'
make: *** [all] Error 2
```

enchant_get_version has been introduced in enchant 1.6.0.
