### ISSUE TITLE
Javascript plugin does not compile with v8 version 3.30.33.16

### ISSUE THREAD

**Issue by flashcode** [weechat/weechat#360]
The javascript fails to compile with v8 version 3.30.33.16 and weechat v1.1-151-g9f15851, on Arch Linux:

```
[ 70%] Building CXX object src/plugins/javascript/CMakeFiles/javascript.dir/weechat-js.o
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp: In function ‘void weechat_js_hashtable_map_cb(void*, t_hashtable*, const char*, const char*)’:
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:94:17: error: ‘New’ is not a member of ‘v8::String’
     (*obj)->Set(String::New(key), String::New(value));
                 ^
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:94:35: error: ‘New’ is not a member of ‘v8::String’
     (*obj)->Set(String::New(key), String::New(value));
                                   ^
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp: In function ‘v8::Handle<v8::Object> weechat_js_hashtable_to_object(t_hashtable*)’:
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:104:38: error: no matching function for call to ‘v8::Object::New()’
     Handle<Object> obj = Object::New();
                                      ^
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:104:38: note: candidate is:
In file included from /home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.h:24:0,
                 from /home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:33:
/usr/include/v8.h:2609:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/usr/include/v8.h:2609:24: note:   candidate expects 1 argument, 0 provided
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp: In function ‘void* weechat_js_exec(t_plugin_script*, int, const char*, const char*, void**)’:
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:196:32: error: ‘New’ is not a member of ‘v8::String’
                     argv2[i] = v8::String::New((const char *)argv[i]);
                                ^
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:199:66: error: no matching function for call to ‘v8::Integer::New(int&)’
                     argv2[i] = v8::Integer::New(*((int *)argv[i]));
                                                                  ^
/home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:199:66: note: candidate is:
In file included from /home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.h:24:0,
                 from /home/flashcode/src/weechat/dev/src/plugins/javascript/weechat-js.cpp:33:
/usr/include/v8.h:2224:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/usr/include/v8.h:2224:25: note:   candidate expects 2 arguments, 1 provided
src/plugins/javascript/CMakeFiles/javascript.dir/build.make:54: recipe for target 'src/plugins/javascript/CMakeFiles/javascript.dir/weechat-js.o' failed
make[2]: *** [src/plugins/javascript/CMakeFiles/javascript.dir/weechat-js.o] Error 1
CMakeFiles/Makefile2:1557: recipe for target 'src/plugins/javascript/CMakeFiles/javascript.dir/all' failed
make[1]: *** [src/plugins/javascript/CMakeFiles/javascript.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

This is caused by API changes in v8.
Since there's no version in v8 headers, so it's hard to support multiple version of v8 at same time.

**Comment by flashcode** [comment]
It looks like the deprecated functions in API have been removed in v8 version 3.24.4.
So WeeChat currently only supports v8 <= 3.24.3.

**Comment by flashcode** [comment]
Supporting multiple versions of v8 seems hard, since the version is not exported in headers (it is only since a few days, but not for old releases).

**Comment by stfnm** [comment]
The following commit seems to be the first one in v8 to introduce version information as an include header: https://github.com/v8/v8-git-mirror/commit/9dac60ad2d38ae934ea37a5e90096cce8d950e08

So I guess WeeChat could support v8 versions >= 4.3.0 and <= 3.24.3 (implicitly as the "no version information" fallback).

Of course this would leave some versions in between which will remain unsupported forever but I suppose that's still better than only supporting those old versions forever.

**Comment by flashcode** [comment]
@stfnm: yes you're right, I'll do that.

**Comment by asm89** [comment]
@flashcode I was trying to get javascript support working on macOS. The default v8 version installed by homebrew is currently `v8: stable 5.1.281.47`. Are you still looking into supporting newer versions of v8?

**Comment by flashcode** [comment]
@asm89: yes it is still planned.
I don't have lot of free time to work on that, so help is welcome, but I'll implement that in future anyway when I'll have some time.

**Comment by gpavinteractiv** [comment]
Build fails on fedora 26 due to this bug

**Comment by flashcode** [comment]
If needed, you can disable the javascript plugin with this cmake option: `-DENABLE_JAVASCRIPT=OFF`

**Comment by flashcode** [comment]
@KokaKiwi: are you still using this plugin you wrote?
Help is welcome to make the plugin compatible with either old v8 versions (≤ 3.24.3) and newer versions (≥ 4.3.0 or maybe higher), using libnode-dev in Debian ?

**Comment by KokaKiwi** [comment]
tbh it's been long time i touched that stuff, but I'll see ^^

**Comment by flashcode** [comment]
@KokaKiwi: I just pushed a branch `javascript-v8-node` with some changes to support v8 version 6.8.
But for now the javascript requires some extra changes and does not compile (extra compatibility with old v8 versions will be added later, when we managed to compile with v8 version 6.8).

**Comment by shibumi** [comment]
@flashcode are you aware that we ship older versions of nodejs?
```
community/nodejs-lts-carbon 8.16.2-2
    Evented I/O for V8 javascript (LTS release: Carbon)
community/nodejs-lts-dubnium 10.17.0-2
    Evented I/O for V8 javascript (LTS release: Dubnium)
community/nodejs-lts-erbium 12.13.1-1
    Evented I/O for V8 javascript (LTS release: Erbium)
community/nodejs 13.3.0-1 [installed]
    Evented I/O for V8 javascript
```

**Comment by eli-schwartz** [comment]
@shibumi v8 != nodejs

Anyway there are exactly two *.js scripts listed for weechat, and arch has never built with the v8 plugin, so I think we don't really care, and definitely not enough to move https://aur.archlinux.org/packages/v8 to the official repos.

The PKGBUILD change you've linked here is not really about disabling support for php/javascript, anyway, since those were always disabled when building weechat without the relevant build dependencies. It is just that bff40e4c26817a129ae020c5bc4e51fd5d8476f0 caused that to no longer work, and now we've gotta explicitly disable what we don't use.

I think this is a perfectly reasonable state of affairs, unless js turns out to be suddenly a lot more popular for writing weechat scripts than it seems to be today.
