### PR TITLE
core-crypto.c: fix htobe64 for Darwin

### PR DESCRIPTION
**Pull request by barracuda156**
Use correct headers on Darwin

### CODE REVIEW

**Comment by barracuda156** [comment]
Fixes this:
```
cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/build/src/core && /opt/local/bin/ccache /usr/bin/gcc-4.2 -DHAVE_CJSON -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_ICONV -DHAVE_ZSTD -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"4.4.3\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -I/opt/local/include -I/opt/local/include/cjson -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/build -pipe -Os -I/opt/local/include/LegacySupport -DNDEBUG -I/opt/local/include -I/opt/local/include/LegacySupport -fsigned-char -fms-extensions -Wall -Wextra -Werror-implicit-function-declaration -Wformat -Werror=format-security -arch ppc -mmacosx-version-min=10.6 -MD -MT src/core/CMakeFiles/weechat_core.dir/core-config-file.c.o -MF CMakeFiles/weechat_core.dir/core-config-file.c.o.d -o CMakeFiles/weechat_core.dir/core-config-file.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/weechat-4.4.3/src/core/core-config-file.c
[ 82%] Building C object src/core/CMakeFiles/weechat_core.dir/core-crypto.c.o
cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/build/src/core && /opt/local/bin/ccache /usr/bin/gcc-4.2 -DHAVE_CJSON -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_ICONV -DHAVE_ZSTD -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"4.4.3\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -I/opt/local/include -I/opt/local/include/cjson -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/build -pipe -Os -I/opt/local/include/LegacySupport -DNDEBUG -I/opt/local/include -I/opt/local/include/LegacySupport -fsigned-char -fms-extensions -Wall -Wextra -Werror-implicit-function-declaration -Wformat -Werror=format-security -arch ppc -mmacosx-version-min=10.6 -MD -MT src/core/CMakeFiles/weechat_core.dir/core-crypto.c.o -MF CMakeFiles/weechat_core.dir/core-crypto.c.o.d -o CMakeFiles/weechat_core.dir/core-crypto.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/weechat-4.4.3/src/core/core-crypto.c
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/weechat-4.4.3/src/core/core-crypto.c: In function ‘weecrypto_totp_generate_internal’:
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_irc_weechat/weechat/work/weechat-4.4.3/src/core/core-crypto.c:533: error: implicit declaration of function ‘htobe64’
make[2]: *** [src/core/CMakeFiles/weechat_core.dir/core-crypto.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by flashcode** [comment]
Hi,
On which OS is it an issue?
The CI runs on macOS 14 and there's no such issue on this version.

**Comment by barracuda156** [comment]
Thank you for responding. I ran the build on 10.6 locally, but I can confirm that CI pass on macOS 13–15. See: https://github.com/macports/macports-ports/pull/26852
I trust that existing code still works on a subset of systems, but my suggestion works across the board (likely _from 10.4_ up to Sequoia).
