### ISSUE TITLE
error: implicit declaration of function 'mkdtemp' is invalid in C99

### ISSUE THREAD

**Issue by cardi** [weechat/weechat#1662]
## Bug summary

weechat fails to build on macOS 10.15.7 and Xcode 12.0 12A7209 using release v3.2 as well as the latest (e8cdda318fe2a09ff7302c54cdd7900040a8ba5a).

## Steps to reproduce

1. get release tarball and build

    ```bash
    curl -LO https://github.com/weechat/weechat/archive/refs/tags/v3.2.tar.gz
    tar xf v3.2.tar.gz
    cd weechat-3.2
    mkdir build
    cd build
    cmake .. -DENABLE_LUA=OFF \
        -DENABLE_GUILE=OFF \
        -DENABLE_PERL=OFF \
        -DENABLE_PYTHON=OFF \
        -DENABLE_PYTHON2=OFF \
        -DENABLE_RUBY=OFF \
        -DENABLE_SPELL=OFF \
        -DENABLE_TCL=OFF \
        -DENABLE_JAVASCRIPT=OFF \
        -DENABLE_PHP=OFF \
        -DENABLE_MAN=ON
    make
    ```

## Current behavior

```
[  9%] Building C object src/core/CMakeFiles/weechat_core.dir/wee-dir.c.o
/Users/developer/tmp/weechat-3.2/src/core/wee-dir.c:648:24: error: implicit declaration of function 'mkdtemp' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    ptr_weechat_home = mkdtemp (temp_home_template);
                       ^
/Users/developer/tmp/weechat-3.2/src/core/wee-dir.c:648:22: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int'
      [-Wint-conversion]
    ptr_weechat_home = mkdtemp (temp_home_template);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [src/core/CMakeFiles/weechat_core.dir/wee-dir.c.o] Error 1
make[1]: *** [src/core/CMakeFiles/weechat_core.dir/all] Error 2
make: *** [all] Error 2
```

## Expected behavior

weechat should compile successfully.

weechat v3.1 compiles successfully.

## Suggested solutions

weechat successfully builds after including the following in `wee-dir.c`:
```c
#define _DARWIN_C_SOURCE
```

It looks like `#define _XOPEN_SOURCE 700` turns off some other bit that precludes setting `__DARWIN_C_LEVEL` needed for `unistd.h`:
 https://github.com/weechat/weechat/blob/e8cdda318fe2a09ff7302c54cdd7900040a8ba5a/src/core/wee-dir.c#L27-L28

I'm not sure if setting `_DARWIN_C_SOURCE` interferes with `_XOPEN_SOURCE`, but modifying the code to look like the following enables successful compilation on macOS:
```c
/* for nftw() */
#define _XOPEN_SOURCE 700
#if defined(__APPLE__)
#define _DARWIN_C_SOURCE
#endif
```

Additionally, removing `#define _XOPEN_SOURCE 700` (and not adding `_DARWIN_C_SOURCE`) also results in weechat v3.2 compiling successfully on macOS.

## Additional information

The error about `mkdtemp` was previously resolved in https://github.com/weechat/weechat/issues/1308 by including `unistd.h` in weechat.c, but it seems like moving some of the config directory functionality to [wee-dir.c](https://github.com/weechat/weechat/blob/e8cdda318fe2a09ff7302c54cdd7900040a8ba5a/src/core/wee-dir.c) brings it up again.

 https://github.com/weechat/weechat/blob/e8cdda318fe2a09ff7302c54cdd7900040a8ba5a/src/core/wee-dir.c#L648

In particular, `unistd.h` on macOS (`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h`) checks for the following:
```c
/* Darwin extensions */

#if __DARWIN_C_LEVEL >= __DARWIN_C_FULL

[...]

char    *mkdtemp(char *);

[...]
```

---

- WeeChat version: 3.2 and e8cdda318fe2a09ff7302c54cdd7900040a8ba5a
- OS, distribution and version: macOS 10.15.7 19H1030 x86_64
- Terminal: zsh
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
OK, I'll check this (weird because the unistd.h is there, so I wonder why it doesn't work).

It's time to setup macOS build in CI, to track such issues (I don't have access to any macOS myself, so I can not test).

**Comment by cardi** [comment]
Thank you! 0ceccb9798389981832de2453ed818beee2f0c81 builds sucessfully.

**Comment by flashcode** [comment]
OK, great!

I also added build on macOS in CI, so now such regressions are tracked and will be fixed ASAP: bfa0b4376c02fc741b482b0ed4aa94fb7b0e6919
