### PR TITLE
Fix the build with guile-3.0.0.

### PR DESCRIPTION
**Pull request by orbea**
This adds support to cmake for `guile-3.0.0` and adds missing includes which are presumably included with older guile versions.

### CODE REVIEW

File: src/plugins/guile/weechat-guile-api.c [hunk 1]
```diff
@@ -24,6 +24,8 @@
 
 #include <libguile.h>
 #include <time.h>
+#include <stdio.h>
+#include <string.h>
```
Comment (flashcode) [inline src/plugins/guile/weechat-guile-api.c]: Why are these includes now required?

Comment (orbea) [reply src/plugins/guile/weechat-guile-api.c]: @flashcode These files already needed these includes, I suspect they were included somewhere in guile before and now are not.
```
[ 70%] Building C object src/plugins/guile/CMakeFiles/guile.dir/weechat-guile.c.o
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:130:19: error: implicitly declaring library function 'strdup' with type 'char *(const char *)' [-Werror,-Wimplicit-function-declaration]
    temp_buffer = strdup (*guile_buffer_output);
                  ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:130:19: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:150:30: error: implicitly declaring library function 'strlen' with type 'unsigned long (const char *)' [-Werror,-Wimplicit-function-declaration]
                length = 1 + strlen (temp_buffer) + 1;
                             ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:150:30: note: include the header <string.h> or explicitly provide a declaration for 'strlen'
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:154:21: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
                    snprintf (command, length, "%c%s",
                    ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:154:21: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:307:13: error: implicitly declaring library function 'strcmp' with type 'int (const char *, const char *)' [-Werror,-Wimplicit-function-declaration]
        if (strcmp (type_values, WEECHAT_HASHTABLE_STRING) == 0)
            ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:307:13: note: include the header <string.h> or explicitly provide a declaration for 'strcmp'
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:857:17: error: implicitly declaring library function 'strncmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
            if (strncmp (ptr_name, "-q ", 3) == 0)
                ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:857:17: note: include the header <string.h> or explicitly provide a declaration for 'strncmp'
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:1191:5: error: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
    memcpy (data2, data + start, count);
    ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:1191:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:1195:27: error: implicitly declaring library function 'strchr' with type 'char *(const char *, int)' [-Werror,-Wimplicit-function-declaration]
    while ((ptr_newline = strchr (ptr_data, '\n')) != NULL)
                          ^
/tmp/SBo/weechat-2.7/src/plugins/guile/weechat-guile.c:1195:27: note: include the header <string.h> or explicitly provide a declaration for 'strchr'
7 errors generated.
make[2]: *** [src/plugins/guile/CMakeFiles/guile.dir/build.make:63: src/plugins/guile/CMakeFiles/guile.dir/weechat-guile.c.o] Error 1
make[2]: Leaving directory '/tmp/SBo/weechat-2.7/build'
make[1]: *** [CMakeFiles/Makefile2:1636: src/plugins/guile/CMakeFiles/guile.dir/all] Error 2
make[1]: Leaving directory '/tmp/SBo/weechat-2.7/build'
make: *** [Makefile:152: all] Error 2
```

**Comment by orbea** [comment]
I updated the commit for `configure.ac` too.

**Comment by orbea** [comment]
@flashcode Are we still waiting on anything? I'm not sure about the standard practice here.

**Comment by flashcode** [comment]
I wanted to test with Guile 3.0.0, but I don't have enough time (API tests with Guile 3 are OK though).
So I'll just merge as-is and people can report issues if needed.

**Comment by orbea** [comment]
Sounds good, I didn't notice any warnings with the guile code and haven't had any issues locally.

**Comment by dmilith** [comment]
It builds fine with Guile 3.0.4, but have you tried to run weechat with that? On my box (FreeBSD x86_64) I get SEGFAULT until I remove guile.so from lib/weechat/plugins/

**Comment by flashcode** [comment]
@dmilith: could you please get a backtrace with gdb and put it here?
See the doc here: https://weechat.org/files/doc/devel/weechat_user.en.html#report_crashes
Thanks.

**Comment by dmilith** [comment]
It turned out to be my fault - guile supports JIT execution by default which doesn't work well with PAX hardened systems I use. Fixed by just dropping mprotect/ pageexec flags for weechat. No more issues :) Thanks!
